# 交易接口实现类
executor:
  module: trading.executor.mock_executor
  class: MockExecutor
# 策略方法
strategy:
  module: strategies.base_strategy
  function: always_buy
# 自选股票列表
watchlist_path: data/live_trading/watchlist.csv
volume: 100
